// RONUM Quantification v1.0.0
// Semi-automated ImageJ/Fiji macro for cereal rust disease quantification
//
// ImageJ/Fiji macro for guided or unattended batch quantification using
// calibration profiles generated by RONUM Calibration.
//
// Typical workflow:
// 1. Open an image, or select Fast Mode for folder-based batch analysis.
// 2. Run the macro and select a calibration profile.
// 3. Choose input, naming, processing and output options.
// 4. Where required, define the analysis region or leaf selection.
// 5. RONUM detects disease, performs optional post-processing and particle
//    filtering, saves selected QC outputs, and appends measurements to CSV.
//
// The selected RONUM folder should contain Settings/ and Run_Presets/.

requires("1.54");


// ============================================================
// RONUM base paths
// ============================================================

// Choose the main RONUM folder.
// This should contain:
// Settings/
// Run_Presets/

BASE_DIR = getDirectory("Choose main RONUM folder");

if (BASE_DIR == "") {
    exit("No RONUM folder selected.");
}

BASE_DIR = replace(BASE_DIR, "\\", "/");

if (!endsWith(BASE_DIR, "/")) {
    BASE_DIR = BASE_DIR + "/";
}

SETTINGS_DIR = BASE_DIR + "Settings/";
PRESETS_DIR = BASE_DIR + "Run_Presets/";

if (!File.exists(SETTINGS_DIR)) {
    File.makeDirectory(SETTINGS_DIR);
}

if (!File.exists(PRESETS_DIR)) {
    File.makeDirectory(PRESETS_DIR);
}


// ============================================================
// Helper functions
// ============================================================

function cleanName(s) {
    s = replace(s, " ", "_");
    s = replace(s, ":", "-");
    s = replace(s, "/", "-");
    s = replace(s, "\\", "-");
    s = replace(s, "*", "-");
    s = replace(s, "?", "-");
    s = replace(s, "\"", "-");
    s = replace(s, "<", "-");
    s = replace(s, ">", "-");
    s = replace(s, "|", "-");
    return s;
}

function boolFromText(s) {
    // Settings files written on Windows may contain a trailing carriage return
    // (\r) when lines are split only on \n. Strip whitespace/control characters
    // before interpreting saved true/false flags. Without this, e.g.
    // "true\r" is incorrectly read as false and H/S/B pass masks are inverted.
    s = replace(s, "\r", "");
    s = replace(s, "\n", "");
    s = replace(s, "\t", "");
    s = replace(s, " ", "");
    s = toLowerCase(s);
    if (s == "true") return 1;
    if (s == "yes") return 1;
    if (s == "1") return 1;
    return 0;
}

function boolText(v) {
    if (v == 1) return "true";
    return "false";
}

function isImageFile(name) {
    name = toLowerCase(name);

    if (endsWith(name, ".tif")) return 1;
    if (endsWith(name, ".tiff")) return 1;
    if (endsWith(name, ".jpg")) return 1;
    if (endsWith(name, ".jpeg")) return 1;
    if (endsWith(name, ".png")) return 1;
    if (endsWith(name, ".bmp")) return 1;

    return 0;
}

function getSetting(settingsText, key, defaultValue) {
    lines = split(settingsText, "\n");

    for (i = 0; i < lines.length; i++) {
        line = lines[i];

        if (lengthOf(line) > 0) {
            comma = indexOf(line, ",");

            if (comma >= 0) {
                k = substring(line, 0, comma);
                v = substring(line, comma + 1);

                if (k == key) {
                    return v;
                }
            }
        }
    }

    return defaultValue;
}

function appendLine(path, line) {
    File.append(line + "\n", path);
}

function appendSetting(path, key, value) {
    File.append(key + "," + value + "\n", path);
}

function safeNumberString(x) {
    return d2s(x, 6);
}

function makeHeaderIfNeeded(path, header) {
    if (!File.exists(path)) {
        File.append(header + "\n", path);
    }
}

function padNumberString(s, width) {
    while (lengthOf(s) < width) {
        s = "0" + s;
    }
    return s;
}

function xAtY(x1, y1, x2, y2, targetY) {
    if (y2 == y1) return x1;
    return x1 + (targetY - y1) * (x2 - x1) / (y2 - y1);
}

function mmToPixels(mm, unit, pixelWidth) {
    if (unit == "mm") {
        return mm / pixelWidth;
    }
    if (unit == "cm") {
        return (mm / 10) / pixelWidth;
    }
    if (unit == "um" || unit == "micron" || unit == "microns") {
        return (mm * 1000) / pixelWidth;
    }
    if (unit == "inch" || unit == "inches") {
        return (mm / 25.4) / pixelWidth;
    }

    exit("Image scale unit is '" + unit + "'. Set scale to mm or cm first.");
}

function areaMedian(a) {
    n = a.length;

    if (n == 0) return 0;

    Array.sort(a);

    mid = floor(n / 2);

    if (n % 2 == 1) {
        return a[mid];
    } else {
        return (a[mid - 1] + a[mid]) / 2;
    }
}

function imageIDIsOpen(targetID) {
    // ImageJ image IDs can be negative. -1 is used here only as a placeholder.
    if (targetID == -1 || targetID == 0) return false;
    if (nImages() == 0) return false;

    currentTitle = "";
    if (nImages() > 0) currentTitle = getTitle();

    titles = getList("image.titles");
    found = false;

    for (ci = 0; ci < titles.length; ci++) {
        selectWindow(titles[ci]);
        if (getImageID() == targetID) {
            found = true;
            break;
        }
    }

    if (!found && currentTitle != "" && isOpen(currentTitle)) {
        selectWindow(currentTitle);
    }

    return found;
}

function closeImageByID(id) {
    // Safely close an image by ID without erroring if it was already closed.
    // ImageJ image IDs may be negative, so do not test id > 0.
    if (imageIDIsOpen(id)) {
        setOption("Changes", false);
        close();
    }
}

function closeRONUMWindowsExceptQC(keepQC, sourceTitleToKeep) {
    titles = getList("image.titles");

    for (i = titles.length - 1; i >= 0; i--) {
        title = titles[i];

        if (indexOf(title, "RONUM") >= 0) {

            keepThis = false;

            // Do not close the source image, even if its name contains RONUM
            if (title == sourceTitleToKeep) {
                keepThis = true;
            }

            // Keep QC overlay if requested
            if (keepQC && indexOf(title, "overlay") >= 0) {
                keepThis = true;
            }

            if (!keepThis) {
                selectWindow(title);
                setOption("Changes", false);
                close();
            }
        }
    }
}

function uniquePath(path) {
    if (!File.exists(path)) {
        return path;
    }

    dot = lastIndexOf(path, ".");

    if (dot >= 0) {
        stem = substring(path, 0, dot);
        ext = substring(path, dot);
    } else {
        stem = path;
        ext = "";
    }

    n = 2;

    while (true) {
        nText = d2s(n, 0);

        while (lengthOf(nText) < 3) {
            nText = "0" + nText;
        }

        newPath = stem + "_" + nText + ext;

        if (!File.exists(newPath)) {
            return newPath;
        }

        n++;
    }
}

function closeIfOpen(title) {
    if (isOpen(title)) {
        selectWindow(title);
        setOption("Changes", false);
        close();
    }
}

function closeRONUMSavedOutputWindows(keepQC, sourceTitleToKeep) {
    titles = getList("image.titles");

    for (ci = titles.length - 1; ci >= 0; ci--) {
        title = titles[ci];

        keepThis = false;
        closeThis = false;

        if (title == sourceTitleToKeep) keepThis = true;

        // Keep preview/QC overlays only when explicitly requested.
        if (keepQC && (indexOf(title, "_overlay") >= 0 || indexOf(title, "_leaf_detection_QC") >= 0)) {
            keepThis = true;
        }

        // Saved output windows may be renamed by saveAs(), so their titles no longer contain RONUM.
        // These are generated/archive outputs, not source images. Close them after saving unless preview is requested.
        if (indexOf(title, "_raw_strip") >= 0) closeThis = true;
        if (indexOf(title, "_leaf_detection_mask") >= 0) closeThis = true;
        if (indexOf(title, "_leaf_mask") >= 0) closeThis = true;
        if (indexOf(title, "_mask.tif") >= 0) closeThis = true;
        if (indexOf(title, "_mask.tiff") >= 0) closeThis = true;

        if (!keepQC && indexOf(title, "_overlay") >= 0) closeThis = true;
        if (!keepQC && indexOf(title, "_leaf_detection_QC") >= 0) closeThis = true;

        if (closeThis && !keepThis) {
            selectWindow(title);
            setOption("Changes", false);
            close();
        }
    }
}
// ============================================================
// Choose calibration profile
// ============================================================

allFiles = getFileList(SETTINGS_DIR);

// Count csv files
csvCount = 0;
for (i = 0; i < allFiles.length; i++) {
    if (endsWith(allFiles[i], ".csv")) {
        csvCount++;
    }
}

if (csvCount == 0) {
    exit("No calibration profiles found in:\n\n" + SETTINGS_DIR);
}

profiles = newArray(csvCount);
j = 0;

for (i = 0; i < allFiles.length; i++) {
    if (endsWith(allFiles[i], ".csv")) {
        profiles[j] = allFiles[i];
        j++;
    }
}


// ============================================================
// Choose optional run preset
// ============================================================

presetFilesRaw = getFileList(PRESETS_DIR);

presetCount = 1;
for (i = 0; i < presetFilesRaw.length; i++) {
    if (endsWith(presetFilesRaw[i], ".csv")) {
        presetCount++;
    }
}

presetChoices = newArray(presetCount);
presetChoices[0] = "Manual/default settings";

j = 1;
for (i = 0; i < presetFilesRaw.length; i++) {
    if (endsWith(presetFilesRaw[i], ".csv")) {
        presetChoices[j] = presetFilesRaw[i];
        j++;
    }
}

Dialog.create("RONUM Run Preset");
Dialog.addMessage(
    "Here, you can save quantification settings for next time, or use saved settings from previously.\n" +
    "If you do not want to save or use presets, leave Manual/default settings selected."
);
Dialog.addChoice("Load run preset:", presetChoices, presetChoices[0]);
Dialog.addCheckbox("Fast mode - batch a folder of images without per-image prompts", false);
Dialog.addCheckbox("Use output folder saved in preset if available", true);
Dialog.addCheckbox("Save/update run preset after setting options", false);
Dialog.addString("Preset name to save:", "Default_scan_run");
Dialog.addHelp(
    "<html><h2>Run presets</h2>" +
    "<p>A run preset stores the choices made in the following quantification dialogs, including the calibration profile, processing options, naming rules and optionally the output folder.</p>" +
    "<p><b>Manual/default settings</b> loads the normal RONUM defaults. Select an existing CSV preset to reuse a previous workflow.</p>" +
    "<p><b>Fast mode</b> processes every image in a selected folder using one settings profile. It automatically uses the whole image as the leaf-detection region, can detect and quantify multiple separate leaves per image, suppresses per-image prompts, and writes one tidy QuickView row per detected leaf.</p>" +
    "<p>Tick <b>Save/update run preset</b> to save the final choices after all settings and the output folder have been selected.</p></html>"
);
Dialog.show();

selectedPresetFile = Dialog.getChoice();
fastMode = Dialog.getCheckbox();
usePresetOutputDir = Dialog.getCheckbox();
saveRunPreset = Dialog.getCheckbox();
runPresetName = Dialog.getString();
runPresetName = cleanName(runPresetName);

presetText = "";

if (selectedPresetFile != "Manual/default settings") {
    presetPath = PRESETS_DIR + selectedPresetFile;
    if (File.exists(presetPath)) {
        presetText = File.openAsString(presetPath);
    }
}

// Defaults loaded from preset if present, otherwise sensible defaults
presetProfileFile = getSetting(presetText, "profile_file", profiles[0]);
profileDefault = profiles[0];
for (i = 0; i < profiles.length; i++) {
    if (profiles[i] == presetProfileFile) {
        profileDefault = profiles[i];
    }
}

presetOutputDir = getSetting(presetText, "run_output_dir", "");

preCroppedDefault = boolFromText(getSetting(presetText, "pre_cropped", "false"));
doStraightenDefault = boolFromText(getSetting(presetText, "straighten", "false"));
stripLengthMMDefault = parseFloat(getSetting(presetText, "strip_length_mm", "100"));
stripWidthMMDefault = parseFloat(getSetting(presetText, "strip_width_mm", "10"));
overwriteScaleDefault = boolFromText(getSetting(presetText, "overwrite_scale", "true"));
scanPixelsPerMMDefault = parseFloat(getSetting(presetText, "scan_pixels_per_mm", "47.22"));

askSampleIDDefault = boolFromText(getSetting(presetText, "ask_sample_id", "false"));
samplePrefixDefault = getSetting(presetText, "sample_prefix", "VAL_");
sampleNumberDefault = parseFloat(getSetting(presetText, "sample_number", "1"));
padSampleNumberDefault = boolFromText(getSetting(presetText, "pad_sample_number", "true"));
padWidthDefault = parseFloat(getSetting(presetText, "pad_width", "3"));

filenamePatternDefault = getSetting(presetText, "filename_pattern", "originalName_suffix");
fileSuffixDefault = getSetting(presetText, "file_suffix", "RONUM");

runFillHolesDefault = boolFromText(getSetting(presetText, "fill_holes", "true"));
runDespeckleDefault = boolFromText(getSetting(presetText, "despeckle", "true"));
runWatershedDefault = boolFromText(getSetting(presetText, "watershed", "true"));
runSmoothMaskDefault = boolFromText(getSetting(presetText, "smooth_mask", "true"));
smoothRadiusPxDefault = parseFloat(getSetting(presetText, "smooth_radius_px", "3"));

excludeSmallDefault = boolFromText(getSetting(presetText, "exclude_small", "true"));
flagLargeDefault = boolFromText(getSetting(presetText, "flag_large", "true"));
excludeLargeDefault = boolFromText(getSetting(presetText, "exclude_large", "false"));

saveStripDefault = boolFromText(getSetting(presetText, "save_strip", "true"));
saveMaskDefault = boolFromText(getSetting(presetText, "save_mask", "true"));
saveOverlayDefault = boolFromText(getSetting(presetText, "save_overlay", "true"));
saveParticleTableDefault = boolFromText(getSetting(presetText, "save_particle_table", "true"));
saveSummaryDefault = boolFromText(getSetting(presetText, "save_summary", "true"));
showQCDefault = boolFromText(getSetting(presetText, "show_qc", "true"));

// Auto leaf-detection run defaults
autoDetectLeavesDefault = boolFromText(getSetting(presetText, "auto_detect_leaves", "true"));
autoExpectedLeavesDefault = parseFloat(getSetting(presetText, "auto_expected_leaves", "0"));
autoMaxLeavesDefault = parseFloat(getSetting(presetText, "auto_max_leaves", "20"));
removeBackgroundDefault = boolFromText(getSetting(presetText, "remove_background_outside_leaf", "true"));


// ============================================================
// Quantification options dialogs
// ============================================================

// Dialog 1: profile, input mode, auto leaf detection, scale
Dialog.create("RONUM Quantification v1.0.0 - 1/3: Profile and input");

Dialog.addChoice("Calibration profile:", profiles, profileDefault);

Dialog.addMessage("Input / analysis region options:");
Dialog.addCheckbox("Pre-cropped image: use entire current image", preCroppedDefault);
Dialog.addCheckbox("Straighten selected leaf strip", doStraightenDefault);
Dialog.addNumber("Strip length mm:", stripLengthMMDefault);
Dialog.addNumber("Strip width mm:", stripWidthMMDefault);
Dialog.addCheckbox("Set/overwrite image scale for scans", overwriteScaleDefault);
Dialog.addNumber("Scale pixels per mm:", scanPixelsPerMMDefault);

Dialog.addMessage("Auto leaf detection:");
Dialog.addCheckbox("Auto-detect leaves in selected region", autoDetectLeavesDefault);
Dialog.addNumber("Expected leaves, 0 = detect all:", autoExpectedLeavesDefault);
Dialog.addNumber("Maximum leaves to quantify:", autoMaxLeavesDefault);
Dialog.addCheckbox("Remove background outside detected leaf", removeBackgroundDefault);
Dialog.addHelp(
    "<html><h2>Profile and input</h2>" +
    "<p><b>Calibration profile:</b> selects the thresholds and particle-size limits produced by the calibration macro.</p>" +
    "<p><b>Pre-cropped image:</b> analyses the whole current image without asking for a region.</p>" +
    "<p><b>Straighten selected leaf strip:</b> use only when manually tracing a curved strip that should be converted into a straight analysis image.</p>" +
    "<p><b>Auto-detect leaves:</b> finds calibrated leaf objects inside the selected region and quantifies them separately. Leave expected leaves at 0 to accept all valid leaves, or enter the known replicate count as a check.</p>" +
    "<p><b>Remove background:</b> masks pixels outside each detected leaf before disease quantification.</p></html>"
);

Dialog.show();

profileFile = Dialog.getChoice();

preCropped = Dialog.getCheckbox();
doStraighten = Dialog.getCheckbox();
stripLengthMM = Dialog.getNumber();
stripWidthMM = Dialog.getNumber();
overwriteScale = Dialog.getCheckbox();
scanPixelsPerMM = Dialog.getNumber();

autoDetectLeaves = Dialog.getCheckbox();
autoExpectedLeaves = Dialog.getNumber();
autoMaxLeaves = Dialog.getNumber();
removeBackgroundOutsideLeaf = Dialog.getCheckbox();

// Dialog 2: names and filenames
Dialog.create("RONUM Quantification v1.0.0 - 2/3: Names");

Dialog.addMessage(
    "Here, you can choose how the files are saved. Select Ask for sample ID to manually ID each replicate."
);
Dialog.addMessage("Sample ID options:");
Dialog.addCheckbox("Ask for sample ID", askSampleIDDefault);
Dialog.addString("Sample ID prefix:", samplePrefixDefault);
Dialog.addNumber("Default sample number:", sampleNumberDefault);
Dialog.addCheckbox("Pad numeric sample number", padSampleNumberDefault);
Dialog.addNumber("Pad width:", padWidthDefault);

Dialog.addMessage("Filename options:");
nameOptions = newArray(
    "sampleID_only",
    "parentFolder_originalName_sampleID_suffix",
    "experimentName_originalName_sampleID_suffix",
    "profileName_originalName_sampleID_suffix",
    "originalName_sampleID_suffix",
    "originalName_suffix"
);
Dialog.addChoice("Filename pattern:", nameOptions, filenamePatternDefault);
Dialog.addString("File suffix:", fileSuffixDefault);
Dialog.addHelp(
    "<html><h2>Names and filenames</h2>" +
    "<p><b>Ask for sample ID</b> opens a small identification dialog for each replicate. Leave it unticked to use the original image name automatically.</p>" +
    "<p><b>Sample ID prefix and number</b> provide a starting value for sequential manual IDs. Padding converts values such as 1 to 001.</p>" +
    "<p><b>Filename pattern</b> controls which identifiers appear in saved output names. The default, <code>originalName_suffix</code>, preserves the source filename and adds the chosen suffix.</p>" +
    "<p>RONUM will not overwrite an existing file; a numbered ending is added when necessary.</p></html>"
);

Dialog.show();

askSampleID = Dialog.getCheckbox();
samplePrefix = Dialog.getString();
sampleNumber = Dialog.getNumber();
padSampleNumber = Dialog.getCheckbox();
padWidth = Dialog.getNumber();

filenamePattern = Dialog.getChoice();
fileSuffix = Dialog.getString();
fileSuffix = cleanName(fileSuffix);

// Dialog 3: processing and outputs
Dialog.create("RONUM Quantification v1.0.0 - 3/3: Processing and outputs");

Dialog.addMessage("Processing options:");
Dialog.addCheckbox("Fill holes", runFillHolesDefault);
Dialog.addCheckbox("Despeckle", runDespeckleDefault);
Dialog.addCheckbox("Watershed touching particles", runWatershedDefault);
Dialog.addCheckbox("Smooth binary mask before particle analysis", runSmoothMaskDefault);
Dialog.addNumber("Smoothing radius px:", smoothRadiusPxDefault);

Dialog.addMessage("Particle filtering:");
Dialog.addCheckbox("Exclude small particles from final disease area", excludeSmallDefault);
Dialog.addCheckbox("Flag large particles / clusters", flagLargeDefault);
Dialog.addCheckbox("Exclude large particles from final disease area - WARNING", excludeLargeDefault);

Dialog.addMessage("Outputs:");
Dialog.addCheckbox("Save analysis strip/image", saveStripDefault);
Dialog.addCheckbox("Save binary mask", saveMaskDefault);
Dialog.addCheckbox("Generate and save QC overlay", saveOverlayDefault);
Dialog.addCheckbox("Save particle table", saveParticleTableDefault);
Dialog.addCheckbox("Append summary CSV", saveSummaryDefault);
Dialog.addCheckbox("Show QC overlay preview", showQCDefault);
Dialog.addHelp(
    "<html><h2>Processing and outputs</h2>" +
    "<p><b>Fill holes:</b> fills enclosed gaps inside detected disease objects.</p>" +
    "<p><b>Despeckle:</b> applies a light 3-by-3 median filter to remove isolated pixel noise from the binary mask.</p>" +
    "<p><b>Watershed:</b> attempts to divide touching objects at narrow boundaries. It can increase particle counts and should be kept consistent between runs.</p>" +
    "<p><b>Smooth binary mask:</b> applies a median filter of the selected radius before particle measurement, reducing jagged edges and small irregularities.</p>" +
    "<p><b>Exclude small particles:</b> removes objects below the minimum area saved in the calibration profile.</p>" +
    "<p><b>Flag large particles:</b> retains them in disease area but marks probable clusters. <b>Exclude large particles</b> removes them and may underestimate disease.</p>" +
    "<p>The QC overlay is the quickest way to inspect whether detected objects match the source image.</p></html>"
);

Dialog.show();

runFillHoles = Dialog.getCheckbox();
runDespeckle = Dialog.getCheckbox();
runWatershed = Dialog.getCheckbox();
runSmoothMask = Dialog.getCheckbox();
smoothRadiusPx = Dialog.getNumber();

excludeSmall = Dialog.getCheckbox();
flagLargeRun = Dialog.getCheckbox();
excludeLarge = Dialog.getCheckbox();

saveStripRun = Dialog.getCheckbox();
saveMaskRun = Dialog.getCheckbox();
saveOverlayRun = Dialog.getCheckbox();
saveParticleTableRun = Dialog.getCheckbox();
saveSummaryRun = Dialog.getCheckbox();
showQCRun = Dialog.getCheckbox();

// Fast Mode preserves the selected processing/output and leaf-count settings,
// but removes all per-image interaction. Each source image is used in full as
// the leaf-detection region. Any number of separate leaves up to autoMaxLeaves
// can be extracted and quantified independently.
if (fastMode) {
    preCropped = false;
    doStraighten = false;
    autoDetectLeaves = true;
    askSampleID = false;
    showQCRun = false;
}

if (excludeLarge) {
    okLarge = getBoolean(
        "WARNING:\n\n" +
        "You have chosen to exclude large particles from final disease area.\n\n" +
        "Large particles may be real coalesced disease, not error.\n" +
        "This can underestimate total disease area.\n\n" +
        "Continue?"
    );

    if (!okLarge) {
        exit("Quantification cancelled.");
    }
}

if (usePresetOutputDir && presetOutputDir != "") {
    runOutputDir = presetOutputDir;
} else {
    runOutputDir = getDirectory("Choose RONUM output folder for this quantification run");
}

if (runOutputDir == "") {
    exit("No output folder selected.");
}

runOutputDir = replace(runOutputDir, "\\", "/");

if (!endsWith(runOutputDir, "/")) {
    runOutputDir = runOutputDir + "/";
}

// Fast Mode reads all supported images from one folder. Normal mode retains the
// existing open-image workflow.
fastInputDir = "";
fastFiles = newArray(0);
fastFileCount = 0;

if (fastMode) {
    fastInputDir = getDirectory("Choose folder containing cropped images for Fast Mode");
    if (fastInputDir == "") exit("No Fast Mode input folder selected.");

    rawFastFiles = getFileList(fastInputDir);
    tempFastFiles = newArray(rawFastFiles.length);
    for (fi = 0; fi < rawFastFiles.length; fi++) {
        if (isImageFile(rawFastFiles[fi])) {
            tempFastFiles[fastFileCount] = rawFastFiles[fi];
            fastFileCount++;
        }
    }
    if (fastFileCount == 0) exit("No supported images were found in the Fast Mode input folder.");
    fastFiles = Array.trim(tempFastFiles, fastFileCount);
} else {
    if (nImages() == 0) {
        imagePath = File.openDialog("No images are open. Choose an image to quantify");
        if (imagePath == "") exit("No image selected.");
        open(imagePath);
    }
}

// Use selected output folder name as run/experiment name
tempDir = runOutputDir;

if (endsWith(tempDir, "/")) {
    tempDir = substring(tempDir, 0, lengthOf(tempDir) - 1);
}

slash = lastIndexOf(tempDir, "/");

if (slash >= 0) {
    runName = substring(tempDir, slash + 1);
} else {
    runName = tempDir;
}

runName = cleanName(runName);

// Save/update run preset after the user has chosen all run options and output folder
if (saveRunPreset) {
    if (runPresetName == "") {
        exit("Preset name cannot be blank.");
    }

    runPresetPath = PRESETS_DIR + runPresetName + ".csv";

    if (File.exists(runPresetPath)) {
        overwritePreset = getBoolean(
            "Run preset already exists:\n\n" +
            runPresetPath +
            "\n\nOverwrite this preset?"
        );

        if (!overwritePreset) {
            exit("Quantification cancelled. Existing run preset was not overwritten.");
        }

        File.delete(runPresetPath);
    }

    appendSetting(runPresetPath, "preset_name", runPresetName);
    appendSetting(runPresetPath, "profile_file", profileFile);
    appendSetting(runPresetPath, "fast_mode", boolText(fastMode));
    appendSetting(runPresetPath, "run_output_dir", runOutputDir);

    appendSetting(runPresetPath, "pre_cropped", boolText(preCropped));
    appendSetting(runPresetPath, "straighten", boolText(doStraighten));
    appendSetting(runPresetPath, "strip_length_mm", stripLengthMM);
    appendSetting(runPresetPath, "strip_width_mm", stripWidthMM);
    appendSetting(runPresetPath, "overwrite_scale", boolText(overwriteScale));
    appendSetting(runPresetPath, "scan_pixels_per_mm", scanPixelsPerMM);

    appendSetting(runPresetPath, "auto_detect_leaves", boolText(autoDetectLeaves));
    appendSetting(runPresetPath, "auto_expected_leaves", autoExpectedLeaves);
    appendSetting(runPresetPath, "auto_max_leaves", autoMaxLeaves);
    appendSetting(runPresetPath, "remove_background_outside_leaf", boolText(removeBackgroundOutsideLeaf));

    appendSetting(runPresetPath, "ask_sample_id", boolText(askSampleID));
    appendSetting(runPresetPath, "sample_prefix", samplePrefix);
    appendSetting(runPresetPath, "sample_number", sampleNumber);
    appendSetting(runPresetPath, "pad_sample_number", boolText(padSampleNumber));
    appendSetting(runPresetPath, "pad_width", padWidth);

    appendSetting(runPresetPath, "filename_pattern", filenamePattern);
    appendSetting(runPresetPath, "file_suffix", fileSuffix);

    appendSetting(runPresetPath, "fill_holes", boolText(runFillHoles));
    appendSetting(runPresetPath, "despeckle", boolText(runDespeckle));
    appendSetting(runPresetPath, "watershed", boolText(runWatershed));
    appendSetting(runPresetPath, "smooth_mask", boolText(runSmoothMask));
    appendSetting(runPresetPath, "smooth_radius_px", smoothRadiusPx);

    appendSetting(runPresetPath, "exclude_small", boolText(excludeSmall));
    appendSetting(runPresetPath, "flag_large", boolText(flagLargeRun));
    appendSetting(runPresetPath, "exclude_large", boolText(excludeLarge));

    appendSetting(runPresetPath, "save_strip", boolText(saveStripRun));
    appendSetting(runPresetPath, "save_mask", boolText(saveMaskRun));
    appendSetting(runPresetPath, "save_overlay", boolText(saveOverlayRun));
    appendSetting(runPresetPath, "save_particle_table", boolText(saveParticleTableRun));
    appendSetting(runPresetPath, "save_summary", boolText(saveSummaryRun));
    appendSetting(runPresetPath, "show_qc", boolText(showQCRun));
}

// ============================================================
// Read calibration settings
// ============================================================

settingsPath = SETTINGS_DIR + profileFile;
settingsText = File.openAsString(settingsPath);

profileName = getSetting(settingsText, "profile_name", profileFile);
experimentName = getSetting(settingsText, "experiment_name", "Experiment");

experimentName = runName;
experimentDir = runOutputDir;

masksDir = experimentDir + "Masks/";
overlaysDir = experimentDir + "Overlays/";
particlesDir = experimentDir + "Particles/";
stripsDir = experimentDir + "Strips/";
wideCropsDir = experimentDir + "Wide_Crops/";
leafMasksDir = experimentDir + "Leaf_Masks/";
leafDetectionDir = experimentDir + "Leaf_Detection/";
outputDir = experimentDir + "Output/";
logsDir = experimentDir + "Logs/";
qcDir = experimentDir + "QC/";
quickViewDir = experimentDir + "QuickView/";

// Ensure folders exist
if (!File.exists(experimentDir)) File.makeDirectory(experimentDir);
if (!File.exists(masksDir)) File.makeDirectory(masksDir);
if (!File.exists(overlaysDir)) File.makeDirectory(overlaysDir);
if (!File.exists(particlesDir)) File.makeDirectory(particlesDir);
if (!File.exists(stripsDir)) File.makeDirectory(stripsDir);
if (!File.exists(wideCropsDir)) File.makeDirectory(wideCropsDir);
if (!File.exists(leafMasksDir)) File.makeDirectory(leafMasksDir);
if (!File.exists(leafDetectionDir)) File.makeDirectory(leafDetectionDir);
if (!File.exists(outputDir)) File.makeDirectory(outputDir);
if (!File.exists(logsDir)) File.makeDirectory(logsDir);
if (!File.exists(qcDir)) File.makeDirectory(qcDir);
if (!File.exists(quickViewDir)) File.makeDirectory(quickViewDir);

quickViewFile = quickViewDir + experimentName + "_QuickView.csv";
quickViewHeader = "sample_id,source_type,source_image,leaf_number,leaf_area_mm2,final_disease_area_mm2,final_disease_percent,included_particle_count,unfiltered_disease_area_mm2,unfiltered_disease_percent,particle_count";
if (fastMode) makeHeaderIfNeeded(quickViewFile, quickViewHeader);

// Threshold settings
hMin = parseFloat(getSetting(settingsText, "h_min", "0"));
hMax = parseFloat(getSetting(settingsText, "h_max", "255"));
hPass = boolFromText(getSetting(settingsText, "h_pass", "true"));

sMin = parseFloat(getSetting(settingsText, "s_min", "0"));
sMax = parseFloat(getSetting(settingsText, "s_max", "255"));
sPass = boolFromText(getSetting(settingsText, "s_pass", "true"));

bMin = parseFloat(getSetting(settingsText, "b_min", "0"));
bMax = parseFloat(getSetting(settingsText, "b_max", "255"));
bPass = boolFromText(getSetting(settingsText, "b_pass", "true"));

// Leaf detection threshold settings from calibration profile
leafHMin = parseFloat(getSetting(settingsText, "leaf_h_min", "0"));
leafHMax = parseFloat(getSetting(settingsText, "leaf_h_max", "255"));
leafHPass = boolFromText(getSetting(settingsText, "leaf_h_pass", "true"));

leafSMin = parseFloat(getSetting(settingsText, "leaf_s_min", "0"));
leafSMax = parseFloat(getSetting(settingsText, "leaf_s_max", "255"));
leafSPass = boolFromText(getSetting(settingsText, "leaf_s_pass", "true"));

leafBMin = parseFloat(getSetting(settingsText, "leaf_b_min", "0"));
leafBMax = parseFloat(getSetting(settingsText, "leaf_b_max", "255"));
leafBPass = boolFromText(getSetting(settingsText, "leaf_b_pass", "true"));

leafFillHoles = boolFromText(getSetting(settingsText, "leaf_fill_holes", "true"));
leafSmoothMask = boolFromText(getSetting(settingsText, "leaf_smooth_mask", "true"));
leafSmoothRadiusPx = parseFloat(getSetting(settingsText, "leaf_smooth_radius_px", "5"));
leafMinAreaMM2 = parseFloat(getSetting(settingsText, "leaf_min_area_mm2", "25"));
leafMaxAreaMM2 = parseFloat(getSetting(settingsText, "leaf_max_area_mm2", "0"));
leafMinCircularity = parseFloat(getSetting(settingsText, "leaf_min_circularity", "0.00"));

// Particle filter settings
smallFilterArea = parseFloat(getSetting(settingsText, "small_filter_area", "0"));
largeFlagArea = parseFloat(getSetting(settingsText, "large_flag_area", "999999999"));

// Calibration defaults if user left run options as desired
calFilterSmall = boolFromText(getSetting(settingsText, "filter_small_particles", "true"));
calFlagLarge = boolFromText(getSetting(settingsText, "flag_large_particles", "true"));

if (!calFilterSmall) {
    excludeSmall = false;
}

if (!calFlagLarge) {
    flagLargeRun = false;
}


// ============================================================
// Repeat quantification loop
// ============================================================

keepGoing = 1;
runIndex = 0;

while (keepGoing) {

    runIndex++;

    if (fastMode) {
        // Open exactly one source image for this iteration.
        open(fastInputDir + fastFiles[runIndex - 1]);
        run("Select None");
    }

// ============================================================
// Current image information
// ============================================================

sourceImageID = getImageID();
overlayID = -1;
sourceTitle = getTitle();
sourceDir = getDirectory("image");

dot = lastIndexOf(sourceTitle, ".");
if (dot >= 0) {
    sourceNameNoExt = substring(sourceTitle, 0, dot);
} else {
    sourceNameNoExt = sourceTitle;
}

sourceNameNoExt = cleanName(sourceNameNoExt);

// Parent folder of source image
parentFolder = "UnknownFolder";
if (sourceDir != "") {
    tempDir = replace(sourceDir, "\\", "/");
    if (endsWith(tempDir, "/")) {
        tempDir = substring(tempDir, 0, lengthOf(tempDir) - 1);
    }
    slash = lastIndexOf(tempDir, "/");
    if (slash >= 0) {
        parentFolder = substring(tempDir, slash + 1);
    } else {
        parentFolder = tempDir;
    }
}
parentFolder = cleanName(parentFolder);

// ============================================================
// Sample ID and filename base
// ============================================================

sampleID = "";

if (askSampleID) {
    defaultNum = d2s(sampleNumber, 0);

    if (padSampleNumber) {
        defaultNum = padNumberString(defaultNum, padWidth);
    }

    Dialog.create("RONUM Sample ID");
    Dialog.addString("Sample ID:", samplePrefix + defaultNum);
    Dialog.show();

    sampleID = Dialog.getString();
    sampleID = cleanName(sampleID);
}

if (fileSuffix != "") {
    suffixText = "_" + fileSuffix;
} else {
    suffixText = "";
}

if (sampleID != "") {
    sampleText = "_" + sampleID;
} else {
    sampleText = "";
}

if (filenamePattern == "sampleID_only") {
    if (sampleID == "") {
        baseName = sourceNameNoExt + suffixText;
    } else {
        baseName = sampleID + suffixText;
    }
} else if (filenamePattern == "parentFolder_originalName_sampleID_suffix") {
    baseName = parentFolder + "_" + sourceNameNoExt + sampleText + suffixText;
} else if (filenamePattern == "experimentName_originalName_sampleID_suffix") {
    baseName = experimentName + "_" + sourceNameNoExt + sampleText + suffixText;
} else if (filenamePattern == "profileName_originalName_sampleID_suffix") {
    baseName = profileName + "_" + sourceNameNoExt + sampleText + suffixText;
} else if (filenamePattern == "originalName_sampleID_suffix") {
    baseName = sourceNameNoExt + sampleText + suffixText;
} else {
    baseName = sourceNameNoExt + suffixText;
}

baseName = cleanName(baseName);
baseNameRoot = baseName;


// ============================================================
// Create one or more analysis images
// ============================================================

selectImage(sourceImageID);

if (overwriteScale) {
    run("Set Scale...", "distance=" + scanPixelsPerMM + " known=1 unit=mm");
}

getPixelSize(unit, pixelWidth, pixelHeight);

analysisIDs = newArray(1);
leafAreasPx = newArray(1);
leafAreasMM2 = newArray(1);
leafNumbers = newArray(1);
rawStripFiles = newArray(1);

analysisIDs[0] = -1;
leafAreasPx[0] = 0;
leafAreasMM2[0] = 0;
leafNumbers[0] = 1;
rawStripFiles[0] = "";

leafModeCount = 1;
leafCountInImage = 1;
autoRegionID = -1;
leafMaskID = -1;

if (autoDetectLeaves) {

    selectImage(sourceImageID);

    // If the user forgot to select the broad replicate/leaf region, do not close the macro.
    // Prompt them clearly, then let them draw the selection and continue.
    if (fastMode) {
        run("Select None");
        makeRectangle(0, 0, getWidth(), getHeight());
    } else {
        while (selectionType() == -1) {
            setTool("rectangle");
            waitForUser("RONUM auto leaf region",
                "No auto leaf-detection region is currently selected.\n\n" +
                "Draw the broad region containing the leaf or leaves to quantify.\n" +
                "This can be one leaf, several leaves, or the usable part of a dish/scan.\n\n" +
                "When the region is selected, click OK to try now!");
        }
    }

    run("Duplicate...", "title=RONUM_auto_leaf_region");
    autoRegionID = getImageID();

    // Save the full selected replicate/region crop exactly as duplicated from the source image.
    // This preserves the wide crop used for auto leaf selection so the same replicate can be reviewed later.
    if (saveStripRun) {
        selectImage(autoRegionID);
        wideCropFile = uniquePath(wideCropsDir + baseNameRoot + "_wide_crop.tif");
        saveAs("Tiff", wideCropFile);
    } else {
        wideCropFile = "";
    }

    // Build leaf tissue mask from selected region
    selectImage(autoRegionID);
    run("Duplicate...", "title=RONUM_leaf_hsb_work");
    leafHSBID = getImageID();
    run("HSB Stack");

    setSlice(1);
    run("Duplicate...", "title=RONUM_leaf_H_mask");
    leafHMaskID = getImageID();
    setThreshold(leafHMin, leafHMax);
    setOption("BlackBackground", true);
    run("Convert to Mask");
    if (!leafHPass) run("Invert");
    leafHMaskTitle = getTitle();

    selectImage(leafHSBID);
    setSlice(2);
    run("Duplicate...", "title=RONUM_leaf_S_mask");
    leafSMaskID = getImageID();
    setThreshold(leafSMin, leafSMax);
    setOption("BlackBackground", true);
    run("Convert to Mask");
    if (!leafSPass) run("Invert");
    leafSMaskTitle = getTitle();

    selectImage(leafHSBID);
    setSlice(3);
    run("Duplicate...", "title=RONUM_leaf_B_mask");
    leafBMaskID = getImageID();
    setThreshold(leafBMin, leafBMax);
    setOption("BlackBackground", true);
    run("Convert to Mask");
    if (!leafBPass) run("Invert");
    leafBMaskTitle = getTitle();

    imageCalculator("AND create", leafHMaskTitle, leafSMaskTitle);
    rename("RONUM_leaf_HS_mask");
    leafHSMaskID = getImageID();
    leafHSMaskTitle = getTitle();

    imageCalculator("AND create", leafHSMaskTitle, leafBMaskTitle);
    rename("RONUM_leaf_mask");
    leafMaskID = getImageID();

    selectImage(leafMaskID);
    if (leafFillHoles) run("Fill Holes");
    if (leafSmoothMask) {
        run("Median...", "radius=" + leafSmoothRadiusPx);
        setThreshold(128, 255);
        setOption("BlackBackground", true);
        run("Convert to Mask");
    }

    if (saveMaskRun) {
        selectImage(leafMaskID);
        leafMaskFile = uniquePath(leafMasksDir + baseNameRoot + "_leaf_detection_mask.tif");
        saveAs("Tiff", leafMaskFile);
    } else {
        leafMaskFile = "";
    }

    if (isOpen("Results")) {
        selectWindow("Results");
        run("Close");
    }
    if (isOpen("ROI Manager")) {
        roiManager("Reset");
    }

    // Analyze Particles uses calibrated area units when image scale is set.
    // Therefore use mm2 values directly here.
    if (leafMaxAreaMM2 > 0) {
        leafSizeString = d2s(leafMinAreaMM2, 3) + "-" + d2s(leafMaxAreaMM2, 3);
    } else {
        leafSizeString = d2s(leafMinAreaMM2, 3) + "-Infinity";
    }

    run("Set Measurements...", "area centroid redirect=None decimal=6");
    run("Analyze Particles...", "size=" + leafSizeString + " circularity=" + leafMinCircularity + "-1.00 display clear add");

    detectedLeafCount = roiManager("count");

    if (detectedLeafCount == 0) {
        exit("Auto leaf detection found no leaves. Check leaf detection calibration or selected region.");
    }

    if (autoMaxLeaves <= 0) autoMaxLeaves = 20;

    if (detectedLeafCount > autoMaxLeaves) {
        if (fastMode) {
            // Fast Mode must remain non-interactive. Respect the configured safety cap
            // and record the truncation in the Log window rather than pausing the batch.
            print("WARNING: " + sourceTitle + " contains " + detectedLeafCount +
                  " detected leaf objects; Fast Mode will quantify the first " + autoMaxLeaves +
                  " after left-to-right sorting.");
            leafModeCount = autoMaxLeaves;
        } else {
            okTooMany = getBoolean(
                "RONUM detected " + detectedLeafCount + " leaf objects, which is more than the maximum of " + autoMaxLeaves + ".\n\n" +
                "Only the first " + autoMaxLeaves + " objects will be quantified. Continue?"
            );
            if (!okTooMany) exit("Auto leaf quantification cancelled.");
            leafModeCount = autoMaxLeaves;
        }
    } else {
        leafModeCount = detectedLeafCount;
    }

    leafCountInImage = leafModeCount;

    // Analyze Particles/ROI Manager order is not guaranteed to match visual leaf order.
    // Sort detected leaf ROIs left-to-right using centroid X so leaf01, leaf02, etc. are reproducible.
    leafOrder = newArray(detectedLeafCount);
    for (oi = 0; oi < detectedLeafCount; oi++) {
        leafOrder[oi] = oi;
    }

    for (oi = 0; oi < detectedLeafCount; oi++) {
        for (oj = oi + 1; oj < detectedLeafCount; oj++) {
            idxA = leafOrder[oi];
            idxB = leafOrder[oj];
            xA = getResult("X", idxA);
            xB = getResult("X", idxB);
            yA = getResult("Y", idxA);
            yB = getResult("Y", idxB);

            if (xB < xA || (xB == xA && yB < yA)) {
                tempIdx = leafOrder[oi];
                leafOrder[oi] = leafOrder[oj];
                leafOrder[oj] = tempIdx;
            }
        }
    }

    if (autoExpectedLeaves > 0 && detectedLeafCount != autoExpectedLeaves) {
        if (fastMode) {
            // In Fast Mode an expected-count mismatch is a QC warning only; the batch
            // continues and every detected leaf up to autoMaxLeaves is quantified.
            print("WARNING: " + sourceTitle + " expected " + autoExpectedLeaves +
                  " leaves but detected " + detectedLeafCount + ". Continuing Fast Mode.");
        } else {
            okCount = getBoolean(
                "Expected leaves: " + autoExpectedLeaves + "\n" +
                "Detected leaf objects: " + detectedLeafCount + "\n\n" +
                "Continue anyway?"
            );
            if (!okCount) exit("Auto leaf quantification cancelled.");
        }
    }

    // Show numbered detection QC overlay for approval
    selectImage(autoRegionID);
    run("Duplicate...", "title=" + baseNameRoot + "_leaf_detection_QC");
    leafQCID = getImageID();
    Overlay.clear;

    for (li = 0; li < leafModeCount; li++) {
        roiIndex = leafOrder[li];
        roiManager("Select", roiIndex);
        selectImage(leafQCID);
        roiManager("Select", roiIndex);
        Overlay.addSelection("cyan", 2);
        xC = getResult("X", roiIndex);
        yC = getResult("Y", roiIndex);
        makeText(d2s(li + 1, 0), xC, yC);
        Overlay.addSelection("yellow", 1);
        run("Select None");
    }
    Overlay.show;

    if (saveOverlayRun) {
        selectImage(leafQCID);
        leafQCFile = uniquePath(leafDetectionDir + baseNameRoot + "_leaf_detection_QC.tif");
        saveAs("Tiff", leafQCFile);
    } else {
        leafQCFile = "";
    }

    if (!fastMode) {
        okLeaves = getBoolean(
            "Detected leaves: " + detectedLeafCount + "\n" +
            "Leaves to quantify: " + leafModeCount + "\n\n" +
            "Approve these leaf ROIs and continue?"
        );

        if (!okLeaves) {
            exit("Auto leaf quantification cancelled. Adjust selected region or leaf detection calibration.");
        }
    }

    // Leaf-detection QC must be visible for approval above.
    // After approval, close it unless the user explicitly asked to keep QC previews open.
    if (!showQCRun) {
        closeImageByID(leafQCID);
        closeIfOpen(baseNameRoot + "_leaf_detection_QC");
        closeIfOpen(baseNameRoot + "_leaf_detection_QC.tif");
    }

    analysisIDs = newArray(leafModeCount);
    leafAreasPx = newArray(leafModeCount);
    leafAreasMM2 = newArray(leafModeCount);
    leafNumbers = newArray(leafModeCount);
    rawStripFiles = newArray(leafModeCount);

    // Extract every detected leaf BEFORE any pustule analysis is run.
    // This is critical because the stable pustule pipeline resets ROI Manager
    // and replaces leaf ROIs with pustule particle ROIs.
    //
    // For each detected leaf:
    //   1. select the leaf ROI on the original cropped region
    //   2. store its bounds and polygon coordinates
    //   3. duplicate a rectangular crop around that leaf
    //   4. recreate the leaf ROI inside the duplicated crop using relative coordinates
    //   5. invert and clear outside the recreated ROI
    //   6. store the standalone leaf image ID
    //
    // After this loop finishes, the normal stable RONUM pipeline runs on
    // each standalone leaf image. No leaf ROIs are used during pustule analysis.
    for (li = 0; li < leafModeCount; li++) {

        selectImage(autoRegionID);
        roiIndex = leafOrder[li];
        roiManager("Select", roiIndex);

        // Analyze Particles returns calibrated area when image scale is set.
        // With scale in mm, this value is leaf area in mm2.
        leafAreaMM2 = getResult("Area", roiIndex);
        leafAreaPx = leafAreaMM2 / (pixelWidth * pixelHeight);

        leafAreasPx[li] = leafAreaPx;
        leafAreasMM2[li] = leafAreaMM2;
        leafNumbers[li] = li + 1;

        leafIDText = padNumberString(d2s(li + 1, 0), 2);

        // Store leaf ROI geometry in coordinates from the auto-region image.
        getSelectionBounds(leafBX, leafBY, leafBW, leafBH);
        getSelectionCoordinates(xLeaf, yLeaf);

        // Duplicate a rectangular crop around this leaf from the original cropped region.
        selectImage(autoRegionID);
        run("Select None");
        makeRectangle(leafBX, leafBY, leafBW, leafBH);
        run("Duplicate...", "title=RONUM_leaf_analysis_image_" + leafIDText);
        analysisIDs[li] = getImageID();
	selectImage(analysisIDs[li]);

        // Save the raw rectangular leaf crop before any optional background clearing.
        // This is the strip/archive image for later re-analysis of the exact same crop.
        if (saveStripRun) {
            rawStripFile = uniquePath(stripsDir + baseNameRoot + "_leaf" + leafIDText + "_raw_strip.tif");
            saveAs("Tiff", rawStripFile);
            rawStripFiles[li] = rawStripFile;
        } else {
            rawStripFiles[li] = "";
        }

        // Recreate the detected leaf ROI inside the duplicated crop.
        // The detected ROI coordinates were relative to autoRegionID.
        // The duplicated crop begins at leafBX, leafBY, so subtract those offsets.
        if (removeBackgroundOutsideLeaf) {
            nPts = xLeaf.length;
            xRel = newArray(nPts);
            yRel = newArray(nPts);

            for (p = 0; p < nPts; p++) {
                xRel[p] = xLeaf[p] - leafBX;
                yRel[p] = yLeaf[p] - leafBY;
            }

            makeSelection("polygon", xRel, yRel);

            if (selectionType() != -1) {
                setBackgroundColor(0, 0, 0);
                run("Make Inverse");
                run("Clear", "slice");
                run("Select None");
            } else {
                print("WARNING: leaf " + leafIDText + " relative ROI could not be recreated. Background was not cleared.");
            }
        } else {
            run("Select None");
        }
    }

    // Remove leaf-detection temporary windows before the stable disease pipeline.
    closeImageByID(leafHSBID);
    closeImageByID(leafHMaskID);
    closeImageByID(leafSMaskID);
    closeImageByID(leafBMaskID);
    closeImageByID(leafHSMaskID);
    closeImageByID(leafMaskID);

} else if (preCropped) {

    run("Duplicate...", "title=RONUM_analysis_image");
    analysisIDs[0] = getImageID();

} else if (doStraighten) {

    if (selectionType() == -1) {
        setTool("polygon");
        waitForUser(
            "RONUM leaf selection",
            "Draw a 4-point polygon around the leaf/strip region on the current image.\n\n" +
            "The macro will infer the leaf centreline and create a fixed-size straightened strip.\n\n" +
            "Click OK when done."
        );
    }

    if (selectionType() == -1) {
        exit("No polygon selection was made.");
    }

    getSelectionCoordinates(x, y);

    if (x.length != 4) {
        exit("Selection must have exactly 4 points for straightening.");
    }

    // Sort points by Y value
    idx = newArray(0, 1, 2, 3);

    for (i = 0; i < 4; i++) {
        for (j = i + 1; j < 4; j++) {
            if (y[idx[j]] < y[idx[i]]) {
                temp = idx[i];
                idx[i] = idx[j];
                idx[j] = temp;
            }
        }
    }

    t1 = idx[0];
    t2 = idx[1];
    b1 = idx[2];
    b2 = idx[3];

    topMidX = (x[t1] + x[t2]) / 2;
    topMidY = (y[t1] + y[t2]) / 2;

    botMidX = (x[b1] + x[b2]) / 2;
    botMidY = (y[b1] + y[b2]) / 2;

    centreX = (x[0] + x[1] + x[2] + x[3]) / 4;
    centreY = (y[0] + y[1] + y[2] + y[3]) / 4;

    dx = botMidX - topMidX;
    dy = botMidY - topMidY;

    len = sqrt(dx * dx + dy * dy);

    if (len == 0) {
        exit("Could not determine leaf direction. Redraw the polygon.");
    }

    ux = dx / len;
    uy = dy / len;

    stripLengthPx = round(mmToPixels(stripLengthMM, unit, pixelWidth));
    stripWidthPx = round(mmToPixels(stripWidthMM, unit, pixelWidth));

    halfLen = stripLengthPx / 2;

    lineX1 = centreX - ux * halfLen;
    lineY1 = centreY - uy * halfLen;

    lineX2 = centreX + ux * halfLen;
    lineY2 = centreY + uy * halfLen;

    run("Select None");
    makeLine(lineX1, lineY1, lineX2, lineY2);

    run("Straighten...", "line=" + stripWidthPx);

    rename("RONUM_analysis_image");
    analysisIDs[0] = getImageID();

} else {

    // Not pre-cropped and not straightening.
    // Use any active area selection on the source image.

    selectImage(sourceImageID);

    if (selectionType() == -1) {
        waitForUser(
            "RONUM analysis region",
            "Select the region to quantify on the active source image.\n\n" +
            "You may use a rectangle, polygon, freehand selection, oval, or run a macro such as makeRectangle().\n\n" +
            "This image will NOT be straightened.\n\n" +
            "Click OK when the selection is ready."
        );
    }

    // After user interaction, do NOT change image yet.
    // Check the selection on the currently active image first.
    if (selectionType() == -1) {
        exit("No analysis region was selected.");
    }

    // Store whatever image currently has the selection
    selectedImageID = getImageID();

    // Must be an area selection, not a line
    if (selectionType() == 5 || selectionType() == 6 || selectionType() == 7) {
        exit("The selected ROI appears to be a line selection. Please use an area selection.");
    }

    selectImage(selectedImageID);
    run("Duplicate...", "title=RONUM_analysis_image");
    analysisIDs[0] = getImageID();
}

// ============================================================
// Stable RONUM disease pipeline
// ============================================================

for (leafLoopIndex = 0; leafLoopIndex < leafModeCount; leafLoopIndex++) {

    analysisID = analysisIDs[leafLoopIndex];
    currentLeafNumber = leafNumbers[leafLoopIndex];

    // Track temporary/output image IDs explicitly. Some windows are renamed by saveAs(),
    // so closing by title alone can leave saved masks/overlays/strips open.
    hsbID = -1;
    hMaskID = -1;
    sMaskID = -1;
    bMaskID = -1;
    hsMaskID = -1;
    rawMaskID = -1;
    processedMaskID = -1;
    finalMaskID = -1;
    overlayID = -1;

    selectImage(analysisID);
    print("NOW QUANTIFYING LEAF " + currentLeafNumber + " using image: " + getTitle() + " ID: " + analysisID);
    leafAreaPx = leafAreasPx[leafLoopIndex];
    leafAreaMM2 = leafAreasMM2[leafLoopIndex];

    if (autoDetectLeaves) {
        leafIDText = padNumberString(d2s(currentLeafNumber, 0), 2);
        baseName = baseNameRoot + "_leaf" + leafIDText;
    } else {
        baseName = baseNameRoot;
    }

    selectImage(analysisID);
    leafNumber = leafNumbers[leafLoopIndex];
    analysisWidth = getWidth();
    analysisHeight = getHeight();
    analysisAreaPx = analysisWidth * analysisHeight;
    analysisAreaMM2 = analysisAreaPx * pixelWidth * pixelHeight;

// ============================================================
// Save analysis strip/image if requested
// ============================================================

stripFile = "";

if (saveStripRun) {
    if (autoDetectLeaves) {
        // In auto-leaf mode the strip file was already saved before background clearing.
        stripFile = rawStripFiles[leafLoopIndex];
    } else {
        stripFile = uniquePath(stripsDir + baseName + "_strip.tif");
        saveAs("Tiff", stripFile);
    }
}

// ============================================================
// Create HSB threshold mask
// ============================================================

leafIDText = padNumberString(d2s(currentLeafNumber, 0), 2);
tmpTag = "_leaf" + leafIDText;
selectImage(analysisID);
run("Select None");

print("STARTING HSB THRESHOLD FROM IMAGE ID: " + analysisID);
print("STARTING HSB THRESHOLD FROM TITLE: " + getTitle());
print("STARTING HSB WIDTH x HEIGHT: " + getWidth() + " x " + getHeight());

run("Duplicate...", "title=RONUM_hsb_work" + tmpTag);
hsbID = getImageID();

run("HSB Stack");

// Hue mask
setSlice(1);
run("Duplicate...", "title=RONUM_H_mask" + tmpTag);
hMaskID = getImageID();
setThreshold(hMin, hMax);
setOption("BlackBackground", true);
run("Convert to Mask");

if (!hPass) {
    run("Invert");
}

hMaskTitle = getTitle();

// Saturation mask
selectImage(hsbID);
setSlice(2);
run("Duplicate...", "title=RONUM_S_mask" + tmpTag);
sMaskID = getImageID();
setThreshold(sMin, sMax);
setOption("BlackBackground", true);
run("Convert to Mask");

if (!sPass) {
    run("Invert");
}

sMaskTitle = getTitle();

// Brightness mask
selectImage(hsbID);
setSlice(3);
run("Duplicate...", "title=RONUM_B_mask" + tmpTag);
bMaskID = getImageID();
setThreshold(bMin, bMax);
setOption("BlackBackground", true);
run("Convert to Mask");

if (!bPass) {
    run("Invert");
}

bMaskTitle = getTitle();

// Combine masks with AND
imageCalculator("AND create", hMaskTitle, sMaskTitle);
rename("RONUM_HS_mask" + tmpTag);
hsMaskID = getImageID();
hsMaskTitle = getTitle();

imageCalculator("AND create", hsMaskTitle, bMaskTitle);
rename("RONUM_raw_mask" + tmpTag);
rawMaskID = getImageID();


// ============================================================
// Clean mask
// ============================================================

selectImage(rawMaskID);

if (runFillHoles) {
    run("Fill Holes");
}

if (runDespeckle) {
    run("Despeckle");
}

if (runSmoothMask) {
    run("Median...", "radius=" + smoothRadiusPx);
    setThreshold(128, 255);
    setOption("BlackBackground", true);
    run("Convert to Mask");
}

if (runWatershed) {
    run("Watershed");
}

// Save a copy of processed raw mask before particle filtering
selectImage(rawMaskID);
run("Select None");
run("Duplicate...", "title=RONUM_processed_mask" + tmpTag);
processedMaskID = getImageID();


// ============================================================
// Measure raw thresholded disease area
// ============================================================

selectImage(processedMaskID);
run("Create Selection");

rawDiseaseAreaPx = 0;
if (selectionType() != -1) {
    run("Measure");
    rawDiseaseAreaPx = getResult("Area", nResults - 1);
}

rawDiseasePercent = 0;
if (analysisAreaMM2 > 0) rawDiseasePercent = 100 * rawDiseaseAreaPx / analysisAreaMM2;
rawDiseasePercentLeafArea = rawDiseasePercent;
if (autoDetectLeaves && leafAreaMM2 > 0) {
    rawDiseasePercentLeafArea = 100 * rawDiseaseAreaPx / leafAreaMM2;
}


// ============================================================
// Particle analysis
// ============================================================

selectImage(processedMaskID);
run("Select None");
run("Clear Results");

if (isOpen("Results")) {
    selectWindow("Results");
    run("Close");
}

selectImage(processedMaskID);
run("Select None");

run("Set Measurements...", "area mean min centroid redirect=None decimal=6");

// Reset Results and ROI Manager so particle measurements contain only
// detections from the current image.
if (isOpen("Results")) {
    selectWindow("Results");
    run("Close");
}

if (isOpen("ROI Manager")) {
    roiManager("Reset");
}

// Include all particles above 0 for categorisation.
// We will classify areas manually after measurement.
selectImage(processedMaskID);
run("Analyze Particles...", "size=0-Infinity circularity=0.00-1.00 display clear add");

particleCount = nResults;


totalParticleArea = 0;

smallExcludedCount = 0;
smallExcludedArea = 0;

includedCount = 0;
includedArea = 0;

largeFlaggedCount = 0;
largeFlaggedArea = 0;

largeExcludedCount = 0;
largeExcludedArea = 0;

particleAreas = newArray(particleCount);
includedAreas = newArray(0);

for (i = 0; i < particleCount; i++) {
    area = getResult("Area", i);
    particleAreas[i] = area;
    totalParticleArea += area;

    isSmall = 0;
    isLarge = 0;

    if (excludeSmall && area < smallFilterArea) {
        isSmall = 1;
    }

    if (flagLargeRun && area > largeFlagArea) {
        isLarge = 1;
    }

    if (isSmall) {
        smallExcludedCount++;
        smallExcludedArea += area;
    } else if (isLarge) {
        largeFlaggedCount++;
        largeFlaggedArea += area;

        if (excludeLarge) {
            largeExcludedCount++;
            largeExcludedArea += area;
        } else {
            includedCount++;
            includedArea += area;
            includedAreas = Array.concat(includedAreas, area);
        }

    } else {
        includedCount++;
        includedArea += area;
        includedAreas = Array.concat(includedAreas, area);
    }
}

finalDiseaseAreaPx = rawDiseaseAreaPx;

if (excludeSmall) {
    finalDiseaseAreaPx = finalDiseaseAreaPx - smallExcludedArea;
}

if (excludeLarge) {
    finalDiseaseAreaPx = finalDiseaseAreaPx - largeExcludedArea;
}

if (finalDiseaseAreaPx < 0) {
    finalDiseaseAreaPx = 0;
}

finalDiseasePercent = 0;
if (analysisAreaMM2 > 0) finalDiseasePercent = 100 * finalDiseaseAreaPx / analysisAreaMM2;

finalDiseasePercentLeafArea = finalDiseasePercent;
if (autoDetectLeaves && leafAreaMM2 > 0) {
    finalDiseasePercentLeafArea = 100 * finalDiseaseAreaPx / leafAreaMM2;
}

if (includedCount > 0) {
    meanIncludedSize = includedArea / includedCount;
} else {
    meanIncludedSize = 0;
}

medianIncludedSize = areaMedian(includedAreas);

if (particleCount > 0) {
    Array.sort(particleAreas);
    minParticleSize = particleAreas[0];
    maxParticleSize = particleAreas[particleCount - 1];
} else {
    minParticleSize = 0;
    maxParticleSize = 0;
}


// ============================================================
// Save particle table
// ============================================================

particleFile = "";

if (saveParticleTableRun) {
    particleFile = uniquePath(particlesDir + baseName + "_particles.csv");
    File.append("particle_index,area_mm2,category\n", particleFile);

    for (i = 0; i < particleCount; i++) {
        area = getResult("Area", i);

        category = "included";

        if (excludeSmall && area < smallFilterArea) {
            category = "small_excluded";
        } else if (flagLargeRun && area > largeFlagArea) {
            if (excludeLarge) {
                category = "large_excluded";
            } else {
                category = "large_flagged_included";
            }
        }

        File.append(
            (i + 1) + "," +
            safeNumberString(area) + "," +
            category + "\n",
            particleFile
        );
    }
}


// ============================================================
// Create and save final disease mask
// ============================================================

maskFile = "";

selectImage(processedMaskID);
run("Select None");
run("Duplicate...", "title=RONUM_final_mask" + tmpTag);
finalMaskID = getImageID();

// The saved mask represents the processed threshold mask before particle-size
// exclusions. Particle-size filtering is represented in the particle table, QC
// overlay and summary measurements.

if (saveMaskRun) {
    selectImage(finalMaskID);
    run("Select None");
    maskFile = uniquePath(masksDir + baseName + "_mask.tif");
    saveAs("Tiff", maskFile);
}


// ============================================================
// Save category QC overlay
// ============================================================

overlayFile = "";
overlayID = -1;

if (saveOverlayRun || showQCRun) {

    selectImage(analysisID);
    run("Duplicate...", "title=" + baseName + "_overlay");
    overlayID = getImageID();

    // Clear any existing overlay
    Overlay.clear;

    // Draw particle ROIs by category.
    // Yellow = included in final disease area
    // Blue = small excluded
    // Red = large flagged
    // Magenta = large excluded

    for (i = 0; i < particleCount; i++) {

        area = getResult("Area", i);

        category = "included";

        if (excludeSmall && area < smallFilterArea) {
            category = "small_excluded";
        } else if (flagLargeRun && area > largeFlagArea) {
            if (excludeLarge) {
                category = "large_excluded";
            } else {
                category = "large_flagged_included";
            }
        }

        // IMPORTANT: ROI Manager selections are applied to the currently active image.
        // Select the QC overlay image FIRST, then apply the particle ROI.
        // Previously the ROI was selected on the mask and the image was switched
        // afterwards, which could leave the overlay image with a stale selection.
        selectImage(overlayID);
        run("Select None");
        roiManager("Select", i);

        if (category == "included") {
            Overlay.addSelection("yellow", 1);
        } else if (category == "small_excluded") {
            Overlay.addSelection("blue", 1);
        } else if (category == "large_flagged_included") {
            Overlay.addSelection("red", 2);
        } else if (category == "large_excluded") {
            Overlay.addSelection("magenta", 2);
        }
    }

    Overlay.show;

    // Add legend as text overlay
    makeText(
        "yellow = included\nblue = small excluded\nred = large flagged\nmagenta = large excluded",
        10,
        10
    );
    Overlay.addSelection("white", 1);
    run("Select None");

    if (saveOverlayRun) {
      overlayFile = uniquePath(overlaysDir + baseName + "_overlay.tif");
saveAs("Tiff", overlayFile);
    }

    if (!showQCRun) {
        closeImageByID(overlayID);
        closeIfOpen(baseName + "_overlay");
        closeIfOpen(baseName + "_overlay.tif");
    }
}

// ============================================================
// Save summary CSV
// ============================================================

summaryFile = outputDir + experimentName + "_RONUM_summary.csv";

if (saveSummaryRun) {

    header =
        "sample_id,source_image,source_folder,settings_profile,settings_file," +
        "base_name,leaf_number,leaf_count_in_image,leaf_area_px,leaf_area_mm2,final_disease_percent_leaf_area,strip_file,wide_crop_file,leaf_detection_mask_file,leaf_detection_qc_file,mask_file,overlay_file,particle_file," +
        "analysis_width_px,analysis_height_px,analysis_area_px,analysis_area_mm2," +
        "raw_disease_area_mm2,raw_disease_percent," +
        "final_disease_area_mm2,final_disease_percent," +
        "particle_count,included_particle_count,included_particle_area_mm2," +
        "small_excluded_count,small_excluded_area_mm2," +
        "large_flagged_count,large_flagged_area_mm2," +
        "large_excluded_count,large_excluded_area_mm2," +
        "mean_included_particle_size_mm2,median_included_particle_size_mm2," +
        "min_particle_size_mm2,max_particle_size_mm2," +
        "h_min,h_max,h_pass,s_min,s_max,s_pass,b_min,b_max,b_pass," +
        "small_filter_area,large_flag_area," +
        "fill_holes,despeckle,smooth_mask,smooth_radius_px,watershed,exclude_small,flag_large,exclude_large," +
        "pre_cropped,straightened,strip_length_mm,strip_width_mm,overwrite_scale,scan_pixels_per_mm,pixel_width_mm,pixel_height_mm";

    makeHeaderIfNeeded(summaryFile, header);

    if (autoDetectLeaves) {
        stripLengthOut = "";
        stripWidthOut = "";
    } else {
        stripLengthOut = stripLengthMM;
        stripWidthOut = stripWidthMM;
    }

    if (!autoDetectLeaves) {
        wideCropFile = "";
        leafMaskFile = "";
        leafQCFile = "";
    }

    row =
        sampleID + "," +
        sourceTitle + "," +
        parentFolder + "," +
        profileName + "," +
        profileFile + "," +
        baseName + "," +
        leafNumber + "," +
        leafCountInImage + "," +
        safeNumberString(leafAreaPx) + "," +
        safeNumberString(leafAreaMM2) + "," +
        safeNumberString(finalDiseasePercentLeafArea) + "," +
        stripFile + "," +
        wideCropFile + "," +
        leafMaskFile + "," +
        leafQCFile + "," +
        maskFile + "," +
        overlayFile + "," +
        particleFile + "," +

        analysisWidth + "," +
        analysisHeight + "," +
        analysisAreaPx + "," +
        safeNumberString(analysisAreaMM2) + "," +

        safeNumberString(rawDiseaseAreaPx) + "," +
        safeNumberString(rawDiseasePercent) + "," +
        safeNumberString(finalDiseaseAreaPx) + "," +
        safeNumberString(finalDiseasePercent) + "," +

        particleCount + "," +
        includedCount + "," +
        safeNumberString(includedArea) + "," +

        smallExcludedCount + "," +
        safeNumberString(smallExcludedArea) + "," +

        largeFlaggedCount + "," +
        safeNumberString(largeFlaggedArea) + "," +
        largeExcludedCount + "," +
        safeNumberString(largeExcludedArea) + "," +

        safeNumberString(meanIncludedSize) + "," +
        safeNumberString(medianIncludedSize) + "," +
        safeNumberString(minParticleSize) + "," +
        safeNumberString(maxParticleSize) + "," +

        hMin + "," + hMax + "," + boolText(hPass) + "," +
        sMin + "," + sMax + "," + boolText(sPass) + "," +
        bMin + "," + bMax + "," + boolText(bPass) + "," +

        safeNumberString(smallFilterArea) + "," +
        safeNumberString(largeFlagArea) + "," +

        boolText(runFillHoles) + "," +
        boolText(runDespeckle) + "," +
        boolText(runSmoothMask) + "," +
	smoothRadiusPx + "," +
	boolText(runWatershed) + "," +
	boolText(excludeSmall) + "," +
        boolText(flagLargeRun) + "," +
        boolText(excludeLarge) + "," +

        boolText(preCropped) + "," +
        boolText(doStraighten) + "," +
        stripLengthOut + "," +
        stripWidthOut + "," +
        boolText(overwriteScale) + "," +
        scanPixelsPerMM + "," +
        pixelWidth + "," +
        pixelHeight;

    appendLine(summaryFile, row);
}

// Fast Mode QuickView: intentionally small and spreadsheet-ready while the
// normal detailed outputs above remain unchanged.
if (fastMode) {
    quickSampleID = sampleID;
    if (quickSampleID == "") quickSampleID = baseName;

    quickRow =
        quickSampleID + ",RONUM," +
        sourceTitle + "," +
        leafNumber + "," +
        safeNumberString(leafAreaMM2) + "," +
        safeNumberString(finalDiseaseAreaPx) + "," +
        safeNumberString(finalDiseasePercentLeafArea) + "," +
        includedCount + "," +
        safeNumberString(rawDiseaseAreaPx) + "," +
        safeNumberString(rawDiseasePercentLeafArea) + "," +
        particleCount;

    appendLine(quickViewFile, quickRow);
}

// ============================================================
// Cleanup temporary images for this leaf
// ============================================================

leafIDText = padNumberString(d2s(currentLeafNumber, 0), 2);
tmpTag = "_leaf" + leafIDText;

closeIfOpen("RONUM_hsb_work" + tmpTag);
closeIfOpen("RONUM_H_mask" + tmpTag);
closeIfOpen("RONUM_S_mask" + tmpTag);
closeIfOpen("RONUM_B_mask" + tmpTag);
closeIfOpen("RONUM_HS_mask" + tmpTag);
closeIfOpen("RONUM_raw_mask" + tmpTag);
closeIfOpen("RONUM_processed_mask" + tmpTag);
closeIfOpen("RONUM_final_mask" + tmpTag);

// Also close by image ID because saveAs() can rename windows to the output filename,
// which makes title-based cleanup miss them.
closeImageByID(hsbID);
closeImageByID(hMaskID);
closeImageByID(sMaskID);
closeImageByID(bMaskID);
closeImageByID(hsMaskID);
closeImageByID(rawMaskID);
closeImageByID(processedMaskID);
closeImageByID(finalMaskID);

if (!showQCRun) {
    closeImageByID(overlayID);
    closeIfOpen(baseName + "_overlay");
    closeIfOpen(baseName + "_overlay.tif");
}

// Close the per-leaf analysis image/crop after quantification.
// In auto-leaf mode the raw strip has already been saved; in other modes saveAs() may
// have renamed this window to the strip filename, so closing by ID is safest.
closeImageByID(analysisID);

// Do not close all saved-output windows inside the leaf loop.
// In auto-leaf mode, later leaves are pre-extracted and their open analysis windows
// may currently be titled *_raw_strip.tif after saveAs(). Closing all raw-strip
// windows here would delete the queued leaves before they are quantified.

} // end leaf loop

// ============================================================
// Print summary
// ============================================================

print("RONUM quantification complete");
print("Sample ID: " + sampleID);
print("Leaf number: " + leafNumber + " of " + leafCountInImage);
print("Profile: " + profileName);
print("Raw disease area mm2: " + rawDiseaseAreaPx);
print("Raw disease percent: " + rawDiseasePercent);
print("Final disease area mm2: " + finalDiseaseAreaPx);
print("Final disease percent: " + finalDiseasePercent);
print("Particle count: " + particleCount);
print("Included particle count: " + includedCount);
print("Small excluded count: " + smallExcludedCount);
print("Large flagged count: " + largeFlaggedCount);
print("Summary CSV: " + summaryFile);

// ============================================================
// Clean up working windows
// ============================================================

// Close Results table
if (isOpen("Results")) {
    selectWindow("Results");
    run("Close");
}

// Close remaining working/output windows.
// Keep overlay/QC previews open only if Show QC preview is ticked.
if (!showQCRun) {
    closeImageByID(leafQCID);
    closeIfOpen(baseNameRoot + "_leaf_detection_QC");
    closeIfOpen(baseNameRoot + "_leaf_detection_QC.tif");
}
closeImageByID(autoRegionID);
closeIfOpen("RONUM_auto_leaf_region");
closeIfOpen(baseNameRoot + "_wide_crop.tif");

closeRONUMWindowsExceptQC(showQCRun, sourceTitle);
closeRONUMSavedOutputWindows(showQCRun, sourceTitle);

// Return to original image
if (isOpen(sourceTitle)) {
    selectWindow(sourceTitle);
}

// Advance default sample number for the next repeat run
if (askSampleID) {
    sampleNumber = sampleNumber + 1;
}

if (fastMode) {
    // Close the source itself after its outputs have been written, then continue
    // automatically until every file in the selected folder is complete.
    if (isOpen(sourceTitle)) {
        selectWindow(sourceTitle);
        setOption("Changes", false);
        close();
    }
    keepGoing = runIndex < fastFileCount;
} else {
    repeatMessage =
        "Quantification complete.\n\n" +
        "Sample ID: " + sampleID + "\n" +
        "Final disease: " + d2s(finalDiseasePercent, 3) + "%\n" +
        "Included particles: " + includedCount + "\n" +
        "Small excluded: " + smallExcludedCount + "\n" +
        "Large flagged: " + largeFlaggedCount + "\n\n" +
        "Quantify another image/leaf with the same settings?";

    keepGoing = getBoolean(repeatMessage);

    if (keepGoing) {
        if (isOpen(sourceTitle)) {
            selectWindow(sourceTitle);
            run("Select None");
        }

        waitForUser(
            "Next image or leaf",
            "Open or select the next image now.\n\n" +
            "Make sure the image you want to quantify is the active window.\n\n" +
            "If using pre-cropped mode, the active image will be quantified directly.\n\n" +
            "If using straighten or no-straighten mode, RONUM will ask for the next selection after you click OK."
        );
    }
}

} // end repeat loop

if (fastMode) {
    showMessage(
        "RONUM Fast Mode finished",
        "Processed " + fastFileCount + " images. Each detected leaf was quantified separately.\n\n" +
        "Detailed summary:\n" + summaryFile + "\n\n" +
        "QuickView:\n" + quickViewFile
    );
} else {
    showMessage(
        "RONUM finished",
        "Quantification run finished.\n\n" +
        "Summary CSV:\n" + summaryFile
    );
}
